version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    container_name: reels-db