//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::prompt::Entity as Prompt;
pub use super::tag::Entity as Tag;
pub use super::taggable::Entity as Taggable;
pub use super::user::Entity as User;
